# Generated by Django 5.1.4 on 2024-12-12 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="avatar",
            field=models.CharField(
                blank=True,
                help_text="URL профиля пользователя",
                max_length=255,
                null=True,
            ),
        ),
    ]
