# Generated by Django 5.1.4 on 2024-12-30 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_alter_customuser_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="avatar",
            field=models.URLField(
                blank=True,
                help_text="URL профиля пользователя",
                max_length=255,
                null=True,
            ),
        ),
    ]
