services:
  traefik:
    image: traefik:v2.10
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--accesslog=true"
      - "--accesslog.filepath=/logs/access.log"
      - "--accesslog.filters.statusCodes=400-499"
      - "--certificatesresolvers.cloudflareResolver.acme.tlschallenge=true"
      - "--certificatesresolvers.cloudflareResolver.acme.email=your-email@example.com"
      - "--certificatesresolvers.cloudflareResolver.acme.storage=/acme.json"

    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./logs:/logs
    secrets:
      - cloudflare.crt
      - cloudflare.key
    networks:
      - is_schedule_network
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.is_schedule_stack.rule=Host(`is-schedule.updspace.com`)"
        - "traefik.http.routers.is_schedule_stack.entrypoints=websecure"
        - "traefik.http.routers.is_schedule_stack.tls=true"
        - "traefik.http.routers.is_schedule_stack.tls.certresolver=cloudflareResolver"
        - "traefik.http.routers.is_schedule_stack.tls.domains[0].main=is-schedule.updspace.com"
        - "traefik.http.routers.is_schedule_stack.tls.domains[0].sans=*.is-schedule.updspace.com"
        - "traefik.http.routers.is_schedule_stack.tls.options.default.minVersion=VersionTLS12"
        - "traefik.http.routers.is_schedule_stack.tls.stores.default.defaultCertificate.certFile=/run/secrets/cloudflare.crt"
        - "traefik.http.routers.is_schedule_stack.tls.stores.default.defaultCertificate.keyFile=/run/secrets/cloudflare.key"

  backend:
    image: ghcr.io/m4tveevm/is_schedule-backend:latest
    environment:
      - DJANGO_DB_HOST=db
      - DJANGO_DB_NAME=postgres
      - DJANGO_DB_USER=postgres
    networks:
      - is_schedule_network
    deploy:
      replicas: 2
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.backend.rule=Host(`is-schedule.updspace.com`) && PathPrefix(`/api`)"
        - "traefik.http.routers.backend.entrypoints=websecure"
        - "traefik.http.routers.backend.tls=true"
        - "traefik.http.routers.backend.tls.certresolver=cloudflareResolver"
        - "traefik.http.services.backend.loadbalancer.server.port=8000"
      secrets:
        - pg_password
        - django_secret

  frontend:
    image: ghcr.io/m4tveevm/is_schedule-frontend:latest
    environment:
      - REACT_APP_BACKEND_URL=https://is-schedule.updspace.com/api/
    networks:
      - is_schedule_network
    deploy:
      replicas: 2
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.frontend.rule=Host(`is-schedule.updspace.com`)"
        - "traefik.http.routers.frontend.entrypoints=websecure"
        - "traefik.http.routers.frontend.tls=true"
        - "traefik.http.routers.frontend.tls.certresolver=cloudflareResolver"
        - "traefik.http.services.frontend.loadbalancer.server.port=80"

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=/run/secrets/pg_password
    networks:
      - is_schedule_network
    deploy:
      restart_policy:
        condition: any

networks:
  is_schedule_network:
    external: true
    name: is_schedule_network

volumes:
  postgres_data:

secrets:
  pg_password:
    external: true
  django_secret:
    external: true
  cloudflare.crt:
    external: true
  cloudflare.key:
    external: true
