# Generated by Django 5.1.4 on 2025-01-05 03:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("educational_plan", "0001_initial"),
        ("group_educational_plan", "0001_initial"),
        ("teacher", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BrigadeAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "brigade_number",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "Бригада 1"),
                            (2, "Бригада 2"),
                            (3, "Бригада 3"),
                        ]
                    ),
                ),
                (
                    "educational_plan_entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="educational_plan.educationalplanentry",
                    ),
                ),
                (
                    "group_educational_plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="group_educational_plan.groupeducationalplan",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="teacher.teacher",
                    ),
                ),
            ],
        ),
    ]
