# Generated by Django 5.2.4 on 2025-08-30 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("subject", "0001_initial"),
        ("teacher", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TeacherProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="subject.subject",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profiles",
                        to="teacher.teacher",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TeacherProfileAmount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "lesson_type",
                    models.CharField(
                        choices=[
                            ("УП", "Учебная практика"),
                            ("КЛ", "Контрольная работа / Коллоквиум"),
                            ("ДК", "Другое занятие"),
                        ],
                        max_length=2,
                    ),
                ),
                ("amount", models.IntegerField(default=0)),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="teacher.teacher",
                    ),
                ),
            ],
        ),
    ]
