# Generated by Django 5.1.4 on 2025-01-16 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("educational_plan", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="educationalplanentry",
            name="hours",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="educationalplanentry",
            name="lesson_type",
            field=models.CharField(
                choices=[
                    ("УП", "Учебная практика"),
                    ("КЛ", "Клиническая практика"),
                    ("ДК", "Доклиническая практика"),
                ],
                max_length=2,
            ),
        ),
    ]
