# Generated by Django 5.1.3 on 2024-11-21 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teacher", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="teacher",
            name="employerType",
            field=models.CharField(
                choices=[
                    ("Основной", "Основное место работы"),
                    ("Совместитель", "Совместитель"),
                ],
                default="Совместитель",
            ),
        ),
        migrations.AddField(
            model_name="teacher",
            name="shortname",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
