# Generated by Django 5.1.4 on 2025-01-05 03:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("educational_plan", "0001_initial"),
        ("groups", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="GroupEducationalPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("deadline", models.DateField(blank=True, null=True)),
                (
                    "educational_plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="educational_plan.educationalplan",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="groups.group",
                    ),
                ),
            ],
        ),
    ]
