# Generated by Django 5.1.4 on 2025-01-16 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teacher_profile", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teacherprofileamount",
            name="lesson_type",
            field=models.CharField(
                choices=[
                    ("УП", "Учебная практика"),
                    ("КЛ", "Контрольная работа / Коллоквиум"),
                    ("ДК", "Другое занятие"),
                ],
                default=0,
                max_length=2,
            ),
            preserve_default=False,
        ),
    ]
