name: Deploy to VDS

on:
  push:
    branches: ["master"]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push backend image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./src/Dockerfile
          tags: ghcr.io/${{github.author}}/backend:latest
          push: true

      - name: Build and push frontend image
        uses: docker/build-push-action@v4
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          tags: ghcr.io/${{github.author}}/frontend:latest
          push: true

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.5.6
        with:
          host: ${{ secrets.VDS_HOST }}
          username: ${{ secrets.VDS_USER }}
          key: ${{ secrets.VDS_SSH_KEY }}
          script: |
            docker login ghcr.io -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}
  
            docker pull ghcr.io/${{github.author}}/backend:latest
            docker pull ghcr.io/${{github.author}}/frontend:latest
  
            docker stack deploy -c /home/deploy_user/stack.yml mystack
